<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <None Include="..\HelixToolkit.snk" />
        <Compile Include="..\AssemblyInfo.cs">
            <Link>Properties\AssemblyInfo.cs</Link>
        </Compile>
    </ItemGroup>
  <PropertyGroup>
    <TargetFrameworks>netstandard1.3;netcoreapp2.1;netcoreapp3.1</TargetFrameworks>
    <Copyright>Copyright (C) Helix Toolkit 2019.</Copyright>
    <PackageLicenseUrl></PackageLicenseUrl>
    <PackageProjectUrl>http://www.helix-toolkit.org/</PackageProjectUrl>
    <PackageIconUrl>https://avatars3.githubusercontent.com/u/8432523?s=200&amp;v=4</PackageIconUrl>
    <RepositoryUrl>https://github.com/helix-toolkit/helix-toolkit</RepositoryUrl>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\HelixToolkit.snk</AssemblyOriginatorKeyFile>
    <Company>HelixToolkit</Company>
    <Authors>HelixToolkit Contributors</Authors>
    <Version>0.0.0.1</Version>
    <RepositoryType>git</RepositoryType>
    <PackageTags>SharpDX; DirectX; 3D;</PackageTags>
    <RootNamespace>HelixToolkit.SharpDX.Core</RootNamespace>
    <DelaySign>false</DelaySign>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)|$(Configuration)|$(Platform)'=='netstandard1.3|Debug|AnyCPU'">
    <DefineConstants>TRACE;DEBUG;NETFX_CORE;CORE;SHARPDX;DX11;MSAA;DX11_1;NETSTANDARD1_3</DefineConstants>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <OutputPath>bin\Debug\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(TargetFramework)|$(Configuration)|$(Platform)'=='netstandard1.3|Release|AnyCPU'">
    <DefineConstants>TRACE;NETFX_CORE;CORE;SHARPDX;DX11;MSAA;DX11_1;RELEASE;NETSTANDARD1_3</DefineConstants>
    <DocumentationFile>bin\Release\HelixToolkit.SharpDX.Core.xml</DocumentationFile>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NoWarn>1701;1702;1705;CS1591</NoWarn>
    <OutputPath>bin\Release\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)|$(Configuration)|$(Platform)'=='netcoreapp2.1|Debug|AnyCPU'">
      <DefineConstants>TRACE;DEBUG;NETFX_CORE;CORE;SHARPDX;DX11;MSAA;DX11_1;NETCORE2_1</DefineConstants>
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
      <OutputPath>bin\Debug\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(TargetFramework)|$(Configuration)|$(Platform)'=='netcoreapp2.1|Release|AnyCPU'">
      <DefineConstants>TRACE;NETFX_CORE;CORE;SHARPDX;DX11;MSAA;DX11_1;RELEASE;NETCORE2_1</DefineConstants>
      <DocumentationFile>bin\Release\HelixToolkit.SharpDX.Core.xml</DocumentationFile>
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
      <NoWarn>1701;1702;1705;CS1591</NoWarn>
      <OutputPath>bin\Release\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)|$(Configuration)|$(Platform)'=='netcoreapp3.1|Debug|AnyCPU'">
      <DefineConstants>TRACE;DEBUG;NETFX_CORE;CORE;SHARPDX;DX11;MSAA;DX11_1;NETCORE3_1</DefineConstants>
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
      <OutputPath>bin\Debug\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(TargetFramework)|$(Configuration)|$(Platform)'=='netcoreapp3.1|Release|AnyCPU'">
      <DefineConstants>TRACE;NETFX_CORE;CORE;SHARPDX;DX11;MSAA;DX11_1;RELEASE;NETCORE3_1</DefineConstants>
      <DocumentationFile>bin\Release\HelixToolkit.SharpDX.Core.xml</DocumentationFile>
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
      <NoWarn>1701;1702;1705;CS1591</NoWarn>
      <OutputPath>bin\Release\</OutputPath>
  </PropertyGroup>

  <Import Project="..\HelixToolkit.SharpDX.Shared\HelixToolkit.SharpDX.Shared.projitems" Label="Shared" />
  <Import Project="..\HelixToolkit.Shared\HelixToolkit.Shared.projitems" Label="Shared" />
  
  <ItemGroup>
    <EmbeddedResource Include="Resources\arial.dds" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\arial.fnt" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Cyotek.Drawing.BitmapFont" Version="2.0.0" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="SharpDX.D3DCompiler" Version="4.2.0" />
    <PackageReference Include="SharpDX.Direct2D1" Version="4.2.0" />
    <PackageReference Include="SharpDX.Direct3D11" Version="4.2.0" />
    <PackageReference Include="SharpDX.DXGI" Version="4.2.0" />
    <PackageReference Include="SharpDX.Mathematics" Version="4.2.0" />
    <PackageReference Include="System.ComponentModel.TypeConverter" Version="4.3.0" />
    <PackageReference Include="System.Drawing.Primitives" Version="4.3.0" />
    <PackageReference Include="System.Private.DataContractSerialization" Version="4.3.0" />
    <PackageReference Include="System.Reflection.TypeExtensions" Version="4.7.0" />
    <PackageReference Include="System.Runtime.Serialization.Primitives" Version="4.3.0" />
    <PackageReference Include="System.Runtime.Serialization.Xml" Version="4.3.0" />
    <PackageReference Include="System.Threading.Tasks.Parallel" Version="4.3.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\HelixToolkit\HelixToolkit.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'netcoreapp2.1'">
    <PackageReference Include="System.CodeDom">
      <Version>4.5.0</Version>
    </PackageReference>
  </ItemGroup>
</Project>
