<Project>
 
 <PropertyGroup>
    <NoWarnBase>CA2213</NoWarnBase>
    <NoWarn Condition="'$(BuildingInsideVisualStudio)' != 'true'">$(NoWarnBase);$(NoWarn);CS8767;NU1701;CS8618;CS8600;CS8602;CS8603;CS8604;CS8625;CS8622;CS8632;CS0618;CS0162;CS0168;CS0219;CS0414;CS0169;CS0067;CS8766;CS0693;CS0809;CS1998;MSB3277</NoWarn>
    <NoWarn Condition="'$(BuildingInsideVisualStudio)' == 'true'">$(NoWarnBase);$(NoWarn);</NoWarn>
    <TestNoWarn>$(NoWarn);8600;8602;8765;8604;8622</TestNoWarn>
  </PropertyGroup>
 
</Project>
